name = "backendfolder"
compatibility_date = "2024-07-23"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWM0MTAyM2QtMTgzNy00YTRlLTgwYjktNTFlZDJjMDFhODQ1IiwidGVuYW50X2lkIjoiZmY2ZTVjMGRjM2Q3MjlhZmE5MjNlZDU1YWY1MjU3MjI1OThhN2FiNzZhZjQ5MWM2YzIwNzc4ODI4N2ExNzBiNiIsImludGVybmFsX3NlY3JldCI6ImRiYWZmZmJkLWQ1MzMtNDNiYy1iYWFkLWIyZGQzMDlkY2NjZCJ9.kYgfUHRsYFI5XrrvPnlI5t015kZh2Da4T-PGgNjTC4k"

CLIENT_ID = '1093839051041-87aul8h96j6d533a6v6mp092q04ajap6.apps.googleusercontent.com'
CLIENT_SECRET = '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'
REDIRECT_URL = 'https://attendance-frontend-7rm1swz4c-sahil9396s-projects.vercel.app'
JWT_KEY = 'h0w1ZGNeKK3j9a1j60AfPY7lyCPl'

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"